Updated tasks file
geodesignhub/urban-sprawl-calculation-service pull request #25
Opened 2023-02-09 11:38 UTC by roshanborkar01

Created tasks file and copy pest the code for processAlgorithum.

2023-02-09 11:44 UTC, roshanborkar01 commented
In the views.py, the  `process_algorithm_async.delay(url, geojson)
` method should call in existing functions or create another to call it.Because it required arguments to get call.

2023-02-11 11:49 UTC, roshanborkar01 commented
As per the next step to create a algorithm paramters object and the call the generate_sprawl_indices method is already there in `[Views.py](https://github.com/geodesignhub/urban-sprawl-calculation-service/blob/5441a4be7cfa3ad9248c539176933bbcaa23d4a3/Server/sprawl_calculator/wup_calculator/views.py#L39)`

2023-02-17 15:13 UTC, hrishiballal requested changes

2023-02-17 15:13 UTC, hrishiballal commented on Server/sprawl_calculator/wup_calculator/tasks.py
> +def process_algorithm_async(url:str, geojson:GeoJSONFeature):
In celery, only strings can be passed so in this case we will pass only the processing_id and the first thing to do is to look up that in the DB and create a `AlgorithmProcessingParameters` object and then call the `generate_sprawl_indices` method.

2023-02-17 15:13 UTC, hrishiballal commented on Server/sprawl_calculator/wup_calculator/tasks.py
> +def process_algorithm_async(url:str, geojson:GeoJSONFeature):
For more information [refer how we do it](https://github.com/geodesignhub/urban-sprawl-calculation-service/blob/master/Server/sprawl_calculator/wup_calculator/views.py#L39) synchronously.

2023-02-17 15:13 UTC, hrishiballal commented on Server/sprawl_calculator/wup_calculator/tasks.py
> +    def processAlgorithm(url:str, geojson:GeoJSONFeature) -> WUPCalculationResult:
See above, this needs to re removed.

2023-02-17 15:13 UTC, hrishiballal commented on Server/sprawl_calculator/sprawl_calculator/settings.py
> +CELERY_RESULT_BACKEND = 'redis://localhost:8000'
Celery broker and URL is on the Redis port, not Django one

2023-02-17 15:13 UTC, hrishiballal commented on Server/sprawl_calculator/sprawl_calculator/settings.py
> +CELERY_BROKER_URL = 'redis://localhost:8000'
Same as below, please fix the port and host

2023-02-17 15:13 UTC, hrishiballal commented on Server/sprawl_calculator/wup_calculator/views.py
> +    process_algorithm_async.delay(url, geojson)
Lets put in the paramter names e.g. `url = url`

2023-02-19 14:21 UTC, hrishiballal commented
We can close off this PR.

2023-02-19 14:21 UTC, closed without merging